/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*definicion de variables del sistema*/
<<<<<<< HEAD

uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;

uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_bin = 0;
uint16_t dummy_16bit_hex = 0;
uint8_t index_8bit = 0;
uint8_t resultado = 0;

uint8_t indexa;
int8_t saafafafaf;

int main(void)
{
	dummy_8bit = 123;
	dummy_16bit = 12345;
	dummy_32bit = 123678;

	dummy_16bit_dec = 32;
	dummy_16bit_bin = 0b100000;
	dummy_16bit_hex = 0x20;

	//RCC->AHB1ENR |= (1 << 0);
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	/*Configuramos el pin A5 como salida*/
	GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos);

	/*Configuramos el pin 5 como salida push-pull*/
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5);

	/**/
	GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos);
	/**/
	GPIOA->OSPEEDR |= ~(0b10 << GPIO_OSPEEDR_OSPEED5_Pos);


	/*Escribir 1 en la posicion 5 -> encender el LED2 (verde)*/
	GPIOA->ODR |= (GPIO_ODR_OD5);






	if (dummy_8bit == 5) {
		dummy_16bit = 50;


	}

	for (index_8bit = 0; index_8bit < 15; index_8bit ++){


	}

	while (resultado){
		for (dummy_8bit = 0; dummy_8bit < 10; dummy_8bit++){
			if (dummy_8bit == 5){
				resultado--;
			}

		}

	}


	switch (index_8bit){ // es bueno para no usar casos anidados como usar muchos if-else varias veces.
	case 1:
		break;
	case 2:
		break;
	case 3:
		break;
	default:

		break;

	}


=======
uint8_t a = 5;
uint8_t b = 0;
uint8_t c = 255;



int main(void)
{
>>>>>>> week-01

	uint8_t r1 = !a;
	uint8_t r2 = !b;
	uint8_t r3 = !c;
	uint8_t r4 = ~c;
	uint8_t r5 = ~a;





    /* Loop forever */
	while(1) {
    }
	return 0;
}




























