/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**/
#include <stdint.h>
#include <stm32f4xx.h>

/*variables*/

volatile uint8_t  aumentar_Counter = 0;
uint32_t counter = 0;


typedef enum {
	GREEN,
	ORANGE,
	RED
} EstadoSemaforo;

EstadoSemaforo new_state = GREEN;
int main(void){

}
void clock(void){

	/*Activando señal de reloj PORTA*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	/*Activando señal de reloj PORTB*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	/*Activando señal de reloj PORTC*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

}

void gpio(void)
{
	/* CONFIGURACION DE PINES DE SALIDA */

	/*Configurando el pin PA0*/

	/*limpiamos la posicion por posibles valores previos*/
	GPIOA->MODER &= ~GPIO_MODER_MODE0_0;
	/* configuramos el pin A0 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE0_0;
	/*Configuramos el pin 0 como salida push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT0;
	/*limpiamos*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED0_0;
	/*configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED0_1;


	/*Configurando el pin PA1*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE1_0;
	/*Configuramos el pin A1 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE1_0;
	/*Configuramos el pin A1 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT1;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED1_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED1_1;

	/*Configurando el pin PA2*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE2_0;
	/*Configuramos el pin A2 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE2_0;
	/*Configuramos el pin A2 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT2;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED2_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED2_1;

	/*Configurando el pin PA3*/

	/*limpiamos la posicion a un valor conocido*/
	GPIOA->MODER &= ~GPIO_MODER_MODE3_0;
	/* configuramos el pin A3 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE3_0;
	/*Configuramos el pin 3 como salida push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT3;
	/*limpiamos*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED3_0;
	/*configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED3_1;


	/*Configurando el pin PA4*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE4_0;
	/*Configuramos el pin A4 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE4_0;
	/*Configuramos el pin A4 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT4;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED4_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED4_1;

	/*Configurando el pin PA8*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE8_0;
	/*Configuramos el pin A8 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE8_0;
	/*Configuramos el pin A8 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT8;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED8_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED8_1;

	/*Configurando el pin PA10*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE10_0;
	/*Configuramos el pin A10 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE10_0;
	/*Configuramos el pin A10 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT10;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED10_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED10_1;



	/*Configurando el pin PB0*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOB->MODER &= ~ GPIO_MODER_MODE0_0;
	/*Configuramos el pin B0 como salida*/
	GPIOB->MODER |= GPIO_MODER_MODE0_0;
	/*Configuramos el pin B0 como salidad push-pull*/
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT0;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED0_0;
	/*Configuramos la velocidad como fast*/
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED0_1;

	/*Configurando el pin PB3*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOB->MODER &= ~ GPIO_MODER_MODE3_0;
	/*Configuramos el pin B3 como salida*/
	GPIOB->MODER |= GPIO_MODER_MODE3_0;
	/*Configuramos el pin B3 como salidad push-pull*/
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT3;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED3_0;
	/*Configuramos la velocidad como fast*/
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED3_1;

	/*Configurando el pin PB4*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOB->MODER &= ~ GPIO_MODER_MODE4_0;
	/*Configuramos el pin B4 como salida*/
	GPIOB->MODER |= GPIO_MODER_MODE4_0;
	/*Configuramos el pin B4 como salidad push-pull*/
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT4;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED4_0;
	/*Configuramos la velocidad como fast*/
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED4_1;

	/*Configurando el pin PB5*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOB->MODER &= ~ GPIO_MODER_MODE5_0;
	/*Configuramos el pin B5 como salida*/
	GPIOB->MODER |= GPIO_MODER_MODE5_0;
	/*Configuramos el pin B5 como salidad push-pull*/
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT5;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED5_0;
	/*Configuramos la velocidad como fast*/
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED5_1;

	/*Configurando el pin PB10*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOB->MODER &= ~ GPIO_MODER_MODE10_0;
	/*Configuramos el pin B10 como salida*/
	GPIOB->MODER |= GPIO_MODER_MODE10_0;
	/*Configuramos el pin B10 como salidad push-pull*/
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT10;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOB->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED10_0;
	/*Configuramos la velocidad como fast*/
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEED10_1;


	/*Configurando el pin PC0*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOC->MODER &= ~ GPIO_MODER_MODE0_0;
	/*Configuramos el pin C0 como salida*/
	GPIOC->MODER |= GPIO_MODER_MODE0_0;
	/*Configuramos el pin C0 como salidad push-pull*/
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT0;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOC->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED0_0;
	/*Configuramos la velocidad como fast*/
	GPIOC->OSPEEDR |= GPIO_OSPEEDR_OSPEED0_1;

	/*Configurando el pin PC1*/

	/*Limpiamos la posición a un valor conocido*/
	GPIOC->MODER &= ~ GPIO_MODER_MODE1_0;
	/*Configuramos el pin C1 como salida*/
	GPIOC->MODER |= GPIO_MODER_MODE1_0;
	/*Configuramos el pin C1 como salidad push-pull*/
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT1;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOC->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED1_0;
	/*Configuramos la velocidad como fast*/
	GPIOC->OSPEEDR |= GPIO_OSPEEDR_OSPEED1_1;

}

void timer(void)
{
	/*Configurando el TIMR3*/
	/*Limpiamos la posicion TIM3EN*/
	RCC->APB1ENR &= ~(RCC_APB1ENR_TIM3EN);
	/*Activamos la señal de reloj para el TIM3*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

	/*Para generar una señal de 250 ms*/
	TIM3->ARR = 999;

	/*La señal incrementa el CNT es de 1Kz*/
	TIM3->PSC = 15999;

	/*Reiniciamos el CNT (aunque no es necesario) ya que cuenta hacia adelante inicalmente.*/
	TIM3->CNT = 0;

	/*COnfiguramos para que el TIM3 cuente de forma ascendente*/
	TIM3->CR1 &= ~(TIM_CR1_DIR);

	/*Limpiamos la posicion ARPE para tenerla en una posicion conocida*/
	TIM3->CR1 &= ~(TIM_CR1_ARPE);

	/*Activamos la interrupcion de actualizacion del TIM3*/
	TIM3->CR1 |= TIM_CR1_ARPE;

	/*Estamos activando la IRQ del TIM3 para que el NVIC reciba señales de ella*/
	__NVIC_EnableIRQ(TIM3_IRQn);

	/*Limpiamos y dejamos en cero*/
	TIM3->SR &= ~(TIM_SR_UIF);

	/*lIMPIAMOS LA POSICION DEL UIF del registro para garantizar iun estado conocido*/
	TIM3->DIER &= ~(TIM_DIER_UIE);

	/*Activamos la interrupcion de actualizacion del TIM3*/
	TIM3->DIER |= TIM_DIER_UIE;

	/*Activamos */
	TIM3->CR1 |= TIM_CR1_CEN;









































	/*Configurando el pin C1 como entrada simple sin push-pull o pull-down*/
	GPIOC->MODER &= ~GPIO_MODER_MODE1;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD1;




	while(1){

		if (aumentar_Counter == 1){
			counter = counter +10;
			aumentar_Counter = 0;
		}

		switch(new_state)
		{
		case GREEN:
			/*Toggle del LED PA5*/
			GPIOA->ODR |= GPIO_ODR_OD5;
			GPIOA->ODR &= ~(GPIO_ODR_OD6 | GPIO_ODR_OD7);
			if (counter >= 5){
				counter = 0;
				new_state = ORANGE;
			}
			break;

		case ORANGE:
			/*Toggle del LED PA6*/
			GPIOA->ODR |= GPIO_ODR_OD6;
			GPIOA->ODR &= ~(GPIO_ODR_OD5 | GPIO_ODR_OD7);
			if(counter >= 2){
				counter = 0;
				new_state = RED;
			}
			break;

		case RED:
			/*Toggle del LED PA7*/
			GPIOA->ODR |= GPIO_ODR_OD7;
			GPIOA->ODR &= ~(GPIO_ODR_OD6 | GPIO_ODR_OD5);
			if(counter >= 5){
				counter = 0;
				new_state = GREEN;
			}
			break;

		default:
			break;
		}
	}
}

/*ISR del TIM3*/
void TIM3_IRQHandler(void){
	/*Evaluamos so la flag UIF esta arriba*/
	if(TIM3->SR && TIM_SR_UIF){
		/*sumamos 1 seg en nuestro caso a counter cada vez que pasa la interrupcion*/
		counter ++;

		/*bajamos la bandera de la interrupcion del TIM3*/
		TIM3->SR &= ~(TIM_SR_UIF);

	}

}

void init_exti(void){

	/*Encendiendo la señal de reloj para el SYSCFG (EXTI)*/
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	/*Configuramos el canal del EXTI*/
	SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI1);
	/*configurando el canal 1 del exti para el puerto C (pin C1)*/
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC);

	/*seleccionando flanco de subida pra ser detectado en el pin C1*/
	EXTI->RTSR |= EXTI_RTSR_TR1;

	/* Registrabndo en el NVIC la interrupcion EXTI1 para que sea atendida*/
	NVIC_EnableIRQ(EXTI1_IRQn);



	/* Activamos la interupcion*/
	EXTI->IMR |= EXTI_IMR_IM1;

}

void EXTI1_IRQHandler(void){

	if (EXTI->PR && EXTI_PR_PR1){
		/** bajamos la bandera de la interrupcion*/
		EXTI->PR |= EXTI_PR_PR1;
		aumentar_Counter ++;
	}
}
