/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stm32f4xx.h>

/*variables*/

volatile uint8_t  aumentar_Counter = 0;
uint32_t counter = 0;


typedef enum {
	GREEN,
	ORANGE,
	RED
} EstadoSemaforo;

EstadoSemaforo new_state = GREEN;

int main(void)
{
	/*Activando señal de reloj*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;


	/*Configurando el pin PA5 para que funcione como salida*/

	/*limpiamos la posicion primero por posibles valores previos*/
	GPIOA->MODER &= ~(0b01 << GPIO_MODER_MODE5_Pos);
	/* configuramos el pin A5 como salida*/
	GPIOA->MODER |= 0b01 << GPIO_MODER_MODE5_Pos;
	/*Configuramos el pin 5 como salida push-pull*/
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5);

	/*limpiamos*/
	GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos);
	/*configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= (0b10 << GPIO_OSPEEDR_OSPEED5_Pos);


	/*Configurando el pin A6 para que funcione como salida*/

	/*Limpiamos la posición 6 a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE6_0;
	/*Configuramos el pin A6 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE6_0;
	/*Configuramos el pin A6 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT6;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED6_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED6_1;

	/*Configurando el pin A7 para que funcione como salida*/

	/*Limpiamos la posición 7 a un valor conocido*/
	GPIOA->MODER &= ~ GPIO_MODER_MODE7_0;
	/*Configuramos el pin A7 como salida*/
	GPIOA->MODER |= GPIO_MODER_MODE7_0;
	/*Configuramos el pin A7	 como salidad push-pull*/
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT7;
	/*Limpiamos a un valor conocido al ospeedr*/
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED7_0;
	/*Configuramos la velocidad como fast*/
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED7_1;

	/*Configurando el pin C1 como entrada simple sin push-pull o pull-down*/
	GPIOC->MODER &= ~GPIO_MODER_MODE1;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD1;


	/*Configurando el TIMR3*/
	/*Limpiamos la posicion TIM3EN*/
	RCC->APB1ENR &= ~(RCC_APB1ENR_TIM3EN);
	/*Activamos la señal de reloj para el TIM3*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

	/*Para generar una señal de 250 ms*/
	TIM3->ARR = 999;

	/*La señal incrementa el CNT es de 1Kz*/
	TIM3->PSC = 15999;

	/*Reiniciamos el CNT (aunque no es necesario) ya que cuenta hacia adelante inicalmente.*/
	TIM3->CNT = 0;

	/*COnfiguramos para que el TIM3 cuente de forma ascendente*/
	TIM3->CR1 &= ~(TIM_CR1_DIR);

	/*Limpiamos la posicion ARPE para tenerla en una posicion conocida*/
	TIM3->CR1 &= ~(TIM_CR1_ARPE);

	/*Activamos la interrupcion de actualizacion del TIM3*/
	TIM3->CR1 |= TIM_CR1_ARPE;


	/*Estamos activando la IRQ del TIM3 para que el NVIC reciba señales de ella*/
	__NVIC_EnableIRQ(TIM3_IRQn);

	/*Limpiamos y dejamos en cero*/
	TIM3->SR &= ~(TIM_SR_UIF);

	/*lIMPIAMOS LA POSICION DEL UIF del registro para garantizar iun estado conocido*/
	TIM3->DIER &= ~(TIM_DIER_UIE);

	/*Activamos la interrupcion de actualizacion del TIM3*/
	TIM3->DIER |= TIM_DIER_UIE;

	/*Activamos */
	TIM3->CR1 |= TIM_CR1_CEN;


	while(1){

		if (aumentar_Counter == 1){
			counter = counter +10;
			aumentar_Counter = 0;
		}

		switch(new_state)
		{
		case GREEN:
			/*Toggle del LED PA5*/
			GPIOA->ODR |= GPIO_ODR_OD5;
			GPIOA->ODR &= ~(GPIO_ODR_OD6 | GPIO_ODR_OD7);
			if (counter >= 5){
				counter = 0;
				new_state = ORANGE;
			}
			break;

		case ORANGE:
			/*Toggle del LED PA6*/
			GPIOA->ODR |= GPIO_ODR_OD6;
			GPIOA->ODR &= ~(GPIO_ODR_OD5 | GPIO_ODR_OD7);
			if(counter >= 2){
				counter = 0;
				new_state = RED;
			}
			break;

		case RED:
			/*Toggle del LED PA7*/
			GPIOA->ODR |= GPIO_ODR_OD7;
			GPIOA->ODR &= ~(GPIO_ODR_OD6 | GPIO_ODR_OD5);
			if(counter >= 5){
				counter = 0;
				new_state = GREEN;
			}
			break;

		default:
			break;
		}
	}
}

/*ISR del TIM3*/
void TIM3_IRQHandler(void){
	/*Evaluamos so la flag UIF esta arriba*/
	if(TIM3->SR && TIM_SR_UIF){
		/*sumamos 1 seg en nuestro caso a counter cada vez que pasa la interrupcion*/
		counter ++;

		/*bajamos la bandera de la interrupcion del TIM3*/
		TIM3->SR &= ~(TIM_SR_UIF);

	}

}

void init_exti(void){

	/*Encendiendo la señal de reloj para el SYSCFG (EXTI)*/
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	/*Configuramos el canal del EXTI*/
	SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI1);
	/*configurando el canal 1 del exti para el puerto C (pin C1)*/
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC);

	/*seleccionando flanco de subida pra ser detectado en el pin C1*/
	EXTI->RTSR |= EXTI_RTSR_TR1;

	/* Registrabndo en el NVIC la interrupcion EXTI1 para que sea atendida*/
	NVIC_EnableIRQ(EXTI1_IRQn);



	/* Activamos la interupcion*/
	EXTI->IMR |= EXTI_IMR_IM1;

}

void EXTI1_IRQHandler(void){

	if (EXTI->PR && EXTI_PR_PR1){
		/** bajamos la bandera de la interrupcion*/
		EXTI->PR |= EXTI_PR_PR1;
		aumentar_Counter ++;
	}
}






















